[package]
name = "there-is-always-a-reason"
authors = ["Rafael Bachmann <rafael.bachmann.93@gmail.com>"]

version = "0.1.0"

edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.74"
